name: Coverage
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - run: | 
          go test -v -coverprofile=coverage.out -covermode=atomic -timeout=1h ./...

          for dir in v[0-9]*;
          do
            test -d "${dir}" || continue

            cd "${dir}" || continue

            go test -v -coverprofile="../coverage-${dir}.out" -covermode=atomic -timeout=1h ./...

            cd ..
          done
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.out, coverage-*
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
