name: Coverage
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - run: | 
          for dir in . v[0-9]*;
          do
            cd "${dir}" || continue

            coverfile="../cov-${dir}"

            if test "${dir}" == ".";
            then
              coverfile="cov"
            fi

            go test -v -coverprofile="${coverfile}" -covermode=atomic -timeout=1h ./...

            test "${dir}" != "." && cd ..
          done
      - uses: coverallsapp/github-action@v2
        with:
          files: cov cov-*
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
